import { ImageData } from "../../types";
import { ImageSourceRequest, ImageSourceStrategy } from "./imageSourceStrategy";
import  { fal } from "@fal-ai/client";


import { getSecretValue } from "../../config/secrets-manager"
export interface FalAIClientOptions {
    modelName?: string;
    systemPrompt?: string;
}

type FalImageResult = {
    images?: {
        url?: string;
        width?: number;
        height?: number;
        content_type?: string;
    }[];
};

export class FalAIImageStrategy implements ImageSourceStrategy {
    private modelName: string;
    private systemPrompt: string;
    private falApiKey: string | null = null;

    public constructor(options: FalAIClientOptions = {}) {
        this.modelName = options.modelName ?? "fal-ai/flux/dev";
        this.systemPrompt = options.systemPrompt ?? this.getDefaultSystemImagePrompt() ;
    }
    
    public setModelName(modelName: string) {
        this.modelName = modelName;
    }

    public async fetchImages(request: ImageSourceRequest): Promise<ImageData[]> {
        if(!this.falApiKey){
            await this.setFalAiKey()
        }
        if (!this.falApiKey) {
            throw new Error("FAL_AI_KEY is missing or could not be loaded from Secrets Manager");
        }
        fal.config({
             credentials: this.falApiKey
        });

        const result = await fal.subscribe(this.modelName, {
        input: {
            prompt: this.systemPrompt + (request.keywords.join(',')),
            negative_prompt:this.getDefaultNegativePrompt(),
            image_size: { width: 1080, height: 1920 }, 
        },
        logs: true,
        onQueueUpdate: (update) => {
            if (update.status === "IN_PROGRESS") {
            update.logs.map((log) => log.message).forEach(console.log);
            }
        },
        });
        const data = result.data as FalImageResult;
        console.log(data);
        console.log(result.requestId);

        return (data.images ?? [])
            .slice(0, request.quantity ?? 1)
            .filter((image) => image?.url)
            .map((image) => ({
                url: image.url as string,
                attribution: "Generated by fal.ai",
                keyword: request.text ?? request.keywords[0] ?? null
            } as ImageData))
    }

    private async setFalAiKey(){
        const key = await getSecretValue('FAL_AI_KEY')
        if (typeof key === "string") {
            this.falApiKey = key.trim()
            return
        }
        this.falApiKey = Object.values(key)[0] as string
    }

    private getDefaultSystemImagePrompt() {
        return [
            "A realistic editorial news photograph.",
            "Depict a specific real-world scene related to the topic.",
            "Focus on environment, objects, and context.",
            "Natural lighting, documentary style.",
            "Vertical composition with space for text.",
            "unreal engine",
            "Topic:"
        ].join("\\n");
    }

    private getDefaultNegativePrompt() {
        return [
            "people",
            "portrait",
            "face",
            "looking at camera",
            "selfie",
            "stock photo",
            "smiling",
            "posed",
            "cartoon",
            "illustration",
            "text",
            "watermark"
        ].join(", ");
    }


}
