import axios from "axios";
import { randomUUID } from "crypto";

import { getSecretValue } from "../../config/secrets-manager";
import { ImageData } from "../../types";
import { ImageSourceRequest, ImageSourceStrategy } from "./imageSourceStrategy";

export interface RunwareClientOptions {
    modelName?: string;
    systemPrompt?: string;
    width?: number;
    height?: number;
    steps?: number;
    CFGScale?: number;
}

type RunwareImageResult = {
    taskType?: string;
    taskUUID?: string;
    imageUUID?: string;
    imageURL?: string;
    NSFWContent?: boolean;
}

type RunwareError = {
    code?: string;
    message?: string;
    parameter?: string;
}

type RunwareResponse = {
    data?: RunwareImageResult[];
    errors?: RunwareError[];
}

const RUNWARE_API_URL = "https://api.runware.ai/v1";

export class RunwareImageStrategy implements ImageSourceStrategy {
    private modelName: string;
    private systemPrompt: string;
    private width: number;
    private height: number;
    private steps: number;
    private CFGScale: number;
    private apiKey: string | null = null;

    public constructor(options: RunwareClientOptions = {}) {
        this.modelName = options.modelName ?? "runware:101@1";
        this.systemPrompt = options.systemPrompt ?? this.getDefaultSystemImagePrompt();
        this.width = options.width ?? 1080;
        this.height = options.height ?? 1920;
        this.steps = options.steps ?? 30;
        this.CFGScale = options.CFGScale ?? 7.5;
    }

    public async fetchImages(request: ImageSourceRequest): Promise<ImageData[]> {
        const quantity = request.quantity ?? 1;
        const prompt = this.buildPrompt(request);

        if (!this.apiKey) {
            await this.setApiKey();
        }

        if (!this.apiKey) {
            throw new Error("RUNWARE_API_KEY is missing or could not be loaded from Secrets Manager");
        }

        const taskUUID = randomUUID();
        const response = await axios.post<RunwareResponse>(
            RUNWARE_API_URL,
            [
                {
                    taskType: "imageInference",
                    taskUUID,
                    outputType: "URL",
                    outputFormat: "JPG",
                    outputQuality: 95,
                    numberResults: quantity,
                    safety: {
                        checkContent: true,
                    },
                    model: this.modelName,
                    positivePrompt: prompt,
                    negativePrompt: this.getDefaultNegativePrompt(),
                    width: this.width,
                    height: this.height,
                    steps: this.steps,
                    CFGScale: this.CFGScale,
                },
            ],
            {
                headers: {
                    Authorization: `Bearer ${this.apiKey}`,
                    "Content-Type": "application/json",
                },
            }
        );

        if (response.data.errors?.length) {
            const errorMessages = response.data.errors
                .map((error) => [error.code, error.parameter, error.message].filter(Boolean).join(": "))
                .join("; ");
            throw new Error(`Runware image generation failed: ${errorMessages}`);
        }

        return (response.data.data ?? [])
            .filter((image) => image.imageURL && !image.NSFWContent)
            .slice(0, quantity)
            .map((image) => ({
                url: image.imageURL as string,
                attribution: `Generated by Runware AI using ${this.modelName}`,
                keyword: request.text ?? request.keywords?.[0] ?? null,
            } as ImageData));
    }

    private buildPrompt(request: ImageSourceRequest) {
        const topic = request.diffusion_prompts?.filter(Boolean).length
            ? request.diffusion_prompts.filter(Boolean).join(". ")
            : request.text?.trim() || request.keywords?.filter(Boolean).join(", ");

        if (!topic) {
            throw new Error("RunwareClient requires text or a keywords array request");
        }

        return `${this.systemPrompt}\n\nTopic:\n${topic}`;
    }

    private async setApiKey() {
        if (process.env.RUNWARE_API_KEY) {
            this.apiKey = process.env.RUNWARE_API_KEY.trim();
            return;
        }

        const key = await getSecretValue("RUNWARE_API_KEY");
        if (typeof key === "string") {
            this.apiKey = key.trim();
            return;
        }
        this.apiKey = String(Object.values(key)[0] ?? "").trim();
    }

    private getDefaultSystemImagePrompt() {
        return [
            "Create a premium vertical editorial image for a social-media news or finance post.",
            "Treat the article-specific brief as the source of truth. Build the image from its named subject, recognition anchor, article-supported visuals, and supported action.",
            "Follow the selected visual strategy, mood, and composition literally. Do not replace them with a generic cinematic technology aesthetic.",
            "Prefer the most realistic and recognizable visual representation of the story. Use symbolism only when the brief explicitly selects symbolic_metaphor.",
            "Accurately include relevant named brand or company logos, products, buildings, landmarks, vehicles, machinery, and national symbols when requested. Never invent a company, product, building sign, or wordmark.",
            "Do not depict people, public figures, faces, portraits, silhouettes, crowds, hands, or human body parts; represent person-led stories with associated non-human visual anchors.",
            "Use credible editorial photography or restrained photoreal editorial art, realistic materials, believable environments, and article-appropriate lighting.",
            "Do not add lightning, storms, glowing energy, particles, futuristic structures, or dramatic effects unless the article-specific brief supports them.",
            "Create one coherent scene rather than a montage. Compose edge-to-edge in vertical 9:16 and keep the primary subject within the upper 60 percent for the post layout.",
            "Do not add headlines, captions, statistics, charts, interfaces, borders, or watermarks. Authentic requested logos and product markings are allowed.",
        ].join("\n");
    }

    private getDefaultNegativePrompt() {
        return [
            "people",
            "person",
            "public figure",
            "face",
            "portrait",
            "crowd",
            "human silhouette",
            "hands",
            "human body parts",
            "stock photo",
            "generic office workers",
            "generic handshake",
            "collage",
            "split screen",
            "caption",
            "headline",
            "large text overlay",
            "random lettering",
            "chart",
            "infographic",
            "user interface",
            "watermark",
            "border",
            "low quality",
            "distorted hands",
            "distorted face",
            "extra limbs",
        ].join(", ");
    }
}
