import axios from "axios";
import { randomUUID } from "crypto";

import { getSecretValue } from "../../config/secrets-manager";
import { ImageData } from "../../types";
import { ImageSourceRequest, ImageSourceStrategy } from "./imageSourceStrategy";

export interface RunwareClientOptions {
    modelName?: string;
    systemPrompt?: string;
    width?: number;
    height?: number;
    steps?: number;
    CFGScale?: number;
}

type RunwareImageResult = {
    taskType?: string;
    taskUUID?: string;
    imageUUID?: string;
    imageURL?: string;
    NSFWContent?: boolean;
}

type RunwareError = {
    code?: string;
    message?: string;
    parameter?: string;
}

type RunwareResponse = {
    data?: RunwareImageResult[];
    errors?: RunwareError[];
}

const RUNWARE_API_URL = "https://api.runware.ai/v1";

export class RunwareImageStrategy implements ImageSourceStrategy {
    private modelName: string;
    private systemPrompt: string;
    private width: number;
    private height: number;
    private steps: number;
    private CFGScale: number;
    private apiKey: string | null = null;

    public constructor(options: RunwareClientOptions = {}) {
        this.modelName = options.modelName ?? "runware:101@1";
        this.systemPrompt = options.systemPrompt ?? this.getDefaultSystemImagePrompt();
        this.width = options.width ?? 1080;
        this.height = options.height ?? 1920;
        this.steps = options.steps ?? 30;
        this.CFGScale = options.CFGScale ?? 7.5;
    }

    public async fetchImages(request: ImageSourceRequest): Promise<ImageData[]> {
        const quantity = request.quantity ?? 1;
        const prompt = this.buildPrompt(request);

        if (!this.apiKey) {
            await this.setApiKey();
        }

        if (!this.apiKey) {
            throw new Error("RUNWARE_API_KEY is missing or could not be loaded from Secrets Manager");
        }

        const taskUUID = randomUUID();
        const response = await axios.post<RunwareResponse>(
            RUNWARE_API_URL,
            [
                {
                    taskType: "imageInference",
                    taskUUID,
                    outputType: "URL",
                    outputFormat: "JPG",
                    outputQuality: 95,
                    numberResults: quantity,
                    safety: {
                        checkContent: true,
                    },
                    model: this.modelName,
                    positivePrompt: prompt,
                    negativePrompt: this.getDefaultNegativePrompt(),
                    width: this.width,
                    height: this.height,
                    steps: this.steps,
                    CFGScale: this.CFGScale,
                },
            ],
            {
                headers: {
                    Authorization: `Bearer ${this.apiKey}`,
                    "Content-Type": "application/json",
                },
            }
        );

        if (response.data.errors?.length) {
            const errorMessages = response.data.errors
                .map((error) => [error.code, error.parameter, error.message].filter(Boolean).join(": "))
                .join("; ");
            throw new Error(`Runware image generation failed: ${errorMessages}`);
        }

        return (response.data.data ?? [])
            .filter((image) => image.imageURL && !image.NSFWContent)
            .slice(0, quantity)
            .map((image) => ({
                url: image.imageURL as string,
                attribution: `Generated by Runware AI using ${this.modelName}`,
                keyword: request.text ?? request.keywords?.[0] ?? null,
            } as ImageData));
    }

    private buildPrompt(request: ImageSourceRequest) {
        const topic = request.text?.trim() || request.keywords?.filter(Boolean).join(", ");

        if (!topic) {
            throw new Error("RunwareClient requires text or a keywords array request");
        }

        return `${this.systemPrompt}\n\nTopic:\n${topic}`;
    }

    private async setApiKey() {
        if (process.env.RUNWARE_API_KEY) {
            this.apiKey = process.env.RUNWARE_API_KEY.trim();
            return;
        }

        const key = await getSecretValue("RUNWARE_API_KEY");
        if (typeof key === "string") {
            this.apiKey = key.trim();
            return;
        }
        this.apiKey = String(Object.values(key)[0] ?? "").trim();
    }

    private getDefaultSystemImagePrompt() {
        return [
            "Create a high-quality vertical editorial image for a social media news post.",
            "The result should look like credible contemporary photography, not a poster, illustration, or stock-photo montage.",
            "Use natural lighting, realistic materials, believable environments, and a clear subject related to the topic.",
            "Compose for a 9:16 frame with enough negative space for overlaid headline text.",
            "Avoid text, logos, watermarks, borders, UI, exaggerated expressions, surreal artifacts, and graphic violence.",
        ].join("\n");
    }

    private getDefaultNegativePrompt() {
        return [
            "text",
            "caption",
            "headline",
            "logo",
            "watermark",
            "poster",
            "cartoon",
            "illustration",
            "low quality",
            "distorted hands",
            "distorted face",
            "extra limbs",
        ].join(", ");
    }
}
