
import type {Post} from "@/types";
import PostCard from "@/components/post-card";
export default function Posts(){

const samplePosts: Post[] = [
  {
    headline: "Stunning Mountain View",
    description: "A breathtaking view of the Alps at sunrise.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Travel"],
    sourcedAt: new Date("2025-09-15T08:00:00Z"),
    imageAttributions: ["Photo by Sean Pierce on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "City Timelapse",
    description: null,
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    mediaType: "Video",
    genre: ["Urban", "Timelapse"],
    sourcedAt: new Date("2025-09-20T12:00:00Z"),
    imageAttributions: null,
    videoAttributions: ["Video by Jane Smith"],
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "Forest Sounds",
    description: "Relaxing audio from a deep forest.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Audio"],
    sourcedAt: new Date("2025-09-25T18:30:00Z"),
    imageAttributions: ["Photo by Forest Inc. on Unsplash"],
    videoAttributions: null,
    audioAttributions: ["Audio by NatureSounds"],
    posted: null,
  },
  {
    headline: "Desert Dunes",
    description: "Golden sand dunes under a clear sky.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Desert"],
    sourcedAt: new Date("2025-09-26T10:00:00Z"),
    imageAttributions: ["Photo by John Doe on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Ocean Waves",
    description: "Crashing waves on a rocky shore.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Ocean"],
    sourcedAt: new Date("2025-09-27T14:00:00Z"),
    imageAttributions: ["Photo by Alex Perez on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Snowy Forest",
    description: "A forest blanketed in snow.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Winter"],
    sourcedAt: new Date("2025-09-28T09:00:00Z"),
    imageAttributions: ["Photo by Tim Gouw on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "Sunset Over Lake",
    description: "A colorful sunset reflected on a calm lake.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Sunset"],
    sourcedAt: new Date("2025-09-29T19:00:00Z"),
    imageAttributions: ["Photo by Jane Smith on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Mountain Lake",
    description: "A crystal clear lake surrounded by mountains.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Lake"],
    sourcedAt: new Date("2025-09-30T11:00:00Z"),
    imageAttributions: ["Photo by Alex Perez on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "City Lights",
    description: "A city skyline illuminated at night.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Urban", "Night"],
    sourcedAt: new Date("2025-10-01T21:00:00Z"),
    imageAttributions: ["Photo by Tim Gouw on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Rainy Street",
    description: "A wet street reflecting neon lights.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Urban", "Rain"],
    sourcedAt: new Date("2025-10-02T16:00:00Z"),
    imageAttributions: ["Photo by Sean Pierce on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "Autumn Leaves",
    description: "Colorful leaves covering the ground.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Autumn"],
    sourcedAt: new Date("2025-10-03T13:00:00Z"),
    imageAttributions: ["Photo by Forest Inc. on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Foggy Morning",
    description: "A foggy morning in the countryside.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Fog"],
    sourcedAt: new Date("2025-10-04T07:00:00Z"),
    imageAttributions: ["Photo by Tim Gouw on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "River Rapids",
    description: "Fast-moving water over rocks.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "River"],
    sourcedAt: new Date("2025-10-05T15:00:00Z"),
    imageAttributions: ["Photo by Alex Perez on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Starry Night",
    description: "A sky full of stars above the mountains.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Night"],
    sourcedAt: new Date("2025-10-06T23:00:00Z"),
    imageAttributions: ["Photo by Sean Pierce on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
  {
    headline: "Countryside Road",
    description: "A winding road through green fields.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Nature", "Countryside"],
    sourcedAt: new Date("2025-10-07T10:00:00Z"),
    imageAttributions: ["Photo by John Doe on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: true,
  },
  {
    headline: "Urban Sunrise",
    description: "Sunrise over a modern city skyline.",
  thumbnailUrl: "https://mediaapibucket.s3.amazonaws.com/posts/1759379917064/post.mp4thumbnail",
    videoUrl: null,
    mediaType: "Image",
    genre: ["Urban", "Sunrise"],
    sourcedAt: new Date("2025-10-08T06:00:00Z"),
    imageAttributions: ["Photo by Tim Gouw on Unsplash"],
    videoAttributions: null,
    audioAttributions: null,
    posted: false,
  },
]


return (
  <div className="w-full h-dvh bg-white grid grid-rows-[5%_95%]">
    <div className="w-full border-b border-b-grey-300 p-5"></div>
    <div className="w-full bg-white overflow-y-auto overscroll-containa grid grid-cols-3 gap-4">
      {samplePosts.map((post, i) => (
        <div className="m-10" key={i}>
          <PostCard post={post} />
        </div>
      ))}
    </div>
  </div>
);


}